### ISSUE TITLE
Problem with spaces in the build path

### ISSUE THREAD

**Issue by MartinJakomin** [UL-FRI/thesis-BDR#15]
The build script doesn't work on Windows, if the build path includes "spaces" 
(e.g. C:\Users\Martin Jakomin\Documents).

Furthermore, I can not properly build the thesis without Admin rights (This needs a confirmation, I am not sure if this is a bug or is this happening just to me).

**Comment by itzsimpl** [comment]
Tested on Windows 10; build works as it should even when path includes "spaces", no admin rights required.
