### ISSUE TITLE
Dynamic chaptermark size

### ISSUE THREAD

**Issue by MartinJakomin** [UL-FRI/thesis-BDR#16]
**Is your feature request related to a problem? Please describe.**
If \title is longer than approximately 80 charachters, then \title overflows the \author in the header.

**Describe the solution you'd like**
Chaptermark size should be dynamic. If \title > 80 size = \footnotesize, If \title > 100 size = \tiny, etc. 

**Describe alternatives you've considered**
I have manually changed the size in FRIteza.cls, but this is not an elegant solution.

>  \renewcommand*{\chaptermark}[1]{
>     \markboth{\iflanguage{slovenian}{\scriptsize\@title@slA}{\footnotesize\@title@enA}}{##1}
>   }

**Comment by itzsimpl** [comment]
Do not modify `FRIthesis.cls`!

The command `\title[]{}` has two parameters, `language={}` and `A={}`, where `A` stands for alternative title. If supplied this, alternative title, is used in running heads. Meaning that, when the original title is too long for the running head, you can provide an alternative (shorter one). In books this is a standard practice. As the alternative title you can provide a different title altogether, but with the same meaning, or simply shorten the title as 
`\title[language=english, A={This is a very long title \ldots}]{This is a very long title, way too long for the running head}`

As an enhancement a future release might include automatic `\ldots` based shortening.
