### ISSUE TITLE
Numbered pages in Approval

### ISSUE THREAD

**Issue by MartinJakomin** [UL-FRI/thesis-BDR#18]
If Approval section is extended to two or more pages, the second page gets numbered (with the roman numeral in the left side of the header). This is a bug, as the approval pages should not be numbered.

**Comment by itzsimpl** [comment]
The Approval section must remain a single page long. If the approval committee consists of less than five members it should always fit on a single page. When there are five members it may overflow. We are working on a solution.

**Comment by itzsimpl** [comment]
Fixed in https://github.com/UL-FRI/thesis-BDR/commit/22dc2d2aa41dd1e601883fd5aec3671c6da510e5.
