### ISSUE TITLE
Missing volume, number and pages of the journal in bibliography

### ISSUE THREAD

**Issue by MartinJakomin** [UL-FRI/thesis-BDR#19]
**Describe the bug**
Using FRIteza bibliography style, if one specifies "doi" field (for the class article), the volume, number and pages are not shown in the bibliography. Same is true for other classes (inproceedings etc.).

**To Reproduce**
To reproduce, use FRIteza bibliography style and any bib entry with doi field.

**Expected behavior**
All fields should be shown in the bibliography.

**Possible Solution**
Modify FRIteza.bst. Example for the class article:

```
FUNCTION {article}
{ output.bibitem
  format.authors "author" output.check
  author format.key output
  format.date "year" output.check
  date.block
  format.title "title" output.check
  new.block
  crossref missing$
    {
      journal
      remove.dots
      "journal" bibinfo.check
      emphasize
      "journal" output.check
      add.blank
      doi missing$
        { format.vol.num.pages output }
        {
         format.vol.num.pages output     # ADD THIS LINE
         format.doi output 
        }
      if$
    }
    { format.article.crossref output.nonnull
      doi missing$
        { format.pages output }
        { format.doi output }
      if$
    }
  if$
  new.block
  format.note output
  format.eprint output
  format.url output
  format.cobiss output
  fin.entry
}
```

**Comment by itzsimpl** [comment]
This is not a bug, but rather a choice of style to keep the bibliography compact. The DOI identifier is a unique digital object identifier. It was devised to always point to the correct work, hence in cases when the DOI is available, volume, number and pages become irrelevant. They were a necessity when browsing journals in paper format, but these days most of the browsing is done online. The same holds for arXiv ids.
