### ISSUE TITLE
Several lists for references and mypreviouspublication

### ISSUE THREAD

**Issue by MakarovIA** [UL-FRI/thesis-BDR#21]
Is it possible to place several reference lists with different text description in \mypreviouspublication command?
For e.g.,
Journal publications
\bibliography{1}
Conference papers
\bibliography{2}
Other papers
\bibliography{3}

It can be easily done via \bibentry, but hacking your template was out of my current .cls knowledge...

Maybe any suggestions how to do this without update for template?

**Comment by itzsimpl** [comment]
The my previous publications section was intentionally made without subsections, so as to remain as concise as possible and to keep the design of all BDR theses alike. Splitting into subsections starts making sense only for large numbers of publications, which is typically not the case when the author is a BDR student (i.e. the \mypreviouspublications section).

**Comment by MakarovIA** [comment]
Any ideas how to do it manually? I have 12 of them and need to somehow highlight core 3-4 form journals.
Also, in comment it is said that you need to include here only first-author publications, but where to place others?

**Comment by itzsimpl** [comment]
The idea is to provide only the most important ones. They need to be related to the subject of the thesis. In your case perhaps only the 3-4 from journals that you mention. All others should be (if they are relevant) listed in the regular bibliography section (if they really are relevant, you will most probably cite them).

**Comment by MakarovIA** [comment]
Ok, I got it, thanks.
