### ISSUE TITLE
TeX Live and MacTeX compatibility

### ISSUE THREAD

**Issue by gw0** [UL-FRI/thesis-BDR#7]
Although I came to the conclusion that using MiKTeX is the best approach. I want to describe my findings for TeX Live (and MacTeX) in this issue, so that anyone interested can start from here.

1. TeX Live does not support the `-include-directory` and `-aux-directory` parameters (it only supports `-output-directory`) (consequently it does not use the `./int` directory).

2. The only way to provide an include directory with classes, styles and fonts is to set the `TEXMFHOME` environment directory (`TEXMFHOME=./texmf`). This directory must follow directory structure from the [TDS specification](https://tug.org/tds/tds.pdf). It can be setup with symbolic links somehow like this:

```bash
cd ./demo-asbook
mkdir -p texmf/tex/latex/
ln -s ../../../../ texmf/tex/latex/FRIteza
mkdir -p texmf/fonts/opentype
ln -s ../../../../fonts/ texmf/fonts/opentype/fonts
mkdir -p texmf/bibtex/bst/
ln -s ../../../../ texmf/bibtex/bst/FRIteza
mkdir -p texmf/bibtex/bib/
ln -s ../../../ texmf/bibtex/bib/local
```

3. The preferred way is therefore to either copy or create symbolic links to all classes, styles and fonts to your target thesis directory (similar outcome as script for Overleaf).

When building with TeX Live one should therefore remove the `-aux-directory` and `-include-directory` parameters. Following compilation errors are related to the `\ProvidesClass` directive. To fix it change it to `\ProvidesClass{FRIteza}[]`.

```
./thesis.tex:12: Missing number, treated as zero.
<to be read again> 
                   v
l.12 
     
./thesis.tex:12: Missing = inserted for \ifnum.
<to be read again> 
                   v
l.12 
...
LaTeX Warning: You have requested, on input line 12, version
               `' of document class FRIteza,
               but only version
               `v2.20190108 XeLaTeX doctoral dissertation class'
               is available.

Overfull \hbox (49.94754pt too wide) in paragraph at lines 12--12
[]\TU/EBGaramond(0)/m/n/9.03374 v2.20190108|
```

**Comment by itzsimpl** [comment]
A possible solution for TeX Live could be setting the `TEXINPUTS`, `BSTINPUTS`, `OPENTYPEFONTS` and `TTFONTS` environment variables (see `latexmkrc` in #8). In addition a possible workaround for the lack of support of the `-aux-directory` parameter is to have a build script which performs three steps (assuming a folder structure of `./int` for intermediate files, and `./out` for output files):

1. create folder `./int`
2. build with `-output-directory=./int`
3. move the generated pdf and synctex fo to folder `./out`
