### ISSUE TITLE
Bibliography style is not compatible with `natbib`

### ISSUE THREAD

**Issue by gw0** [UL-FRI/thesis-BDR#9]
**Is your feature request related to a problem? Please describe.**
For bibliography `natbib` in numerical mode is used, but features from that library can not be used ([natbib docs](http://merkel.texture.rocks/Latex/natbib.php)). For example `\citet{jon90}` should result in `Jones et al. [21]`, but instead `(author?) [21]` appears and a warning like:

```
Package natbib Warning: Author undefined for citation`jon90' 
(natbib)                on page 6 on input line 115.
```

**Describe the solution you'd like**
I would expect that `\citet` and `\citep` work as described for the `natbib` library.

**Describe alternatives you've considered**
The problem is that the `FRIteza.bst` bibliography style is based on `unsrt.bst`, which is NOT compatible with `natbib`. Instead it should be based upon `unsrtnat.bst` ([link](http://tug.ctan.org/macros/latex/contrib/natbib/unsrtnat.bst)) or `plainnat.bst`.

There are no warnings when these bibliography styles are used, but the appearance changes:
```
\bibliographystyle{unsrtnat}
```

**Additional context**
MiKTeX 2.9.6980 on Debian 9.8.

**Comment by itzsimpl** [comment]
The latest release 2e7151f provides support for commands `\citet{}` and others.
